# Multilayer Percepton

### Importacion de librerias

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

2024-05-15 14:41:45.575168: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-15 14:41:45.580034: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-15 14:41:45.631302: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-15 14:41:46.567855: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
tf.__version__

'2.16.1'

## Primera parte -  Preprocesamiento de datos

### Importacion del dataset

In [3]:
dataset = pd.read_csv('dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[ 0.          0.          0.         ...  2.          5.12889855
  85.0209201 ]
 [ 0.          0.          0.         ...  0.         26.03790388
   0.        ]
 [ 0.          0.          0.         ...  2.         12.01603441
  98.30893856]
 ...
 [ 0.66666667  2.          0.88888889 ...  2.          4.67853227
  21.88721922]
 [ 0.          0.          0.         ...  2.          2.75328342
  20.10154132]
 [ 0.          0.          0.         ...  1.          6.49185308
  38.55311175]]


In [5]:
print(y)

[0 0 0 ... 0 0 0]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from joblib import dump
dump(sc, 'std_scaler.bin', compress=True)

['std_scaler.bin']

## Part 2 - Building the ANN

### Initializing the ANN

In [9]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=6, activation='relu'))
model.add(tf.keras.layers.Dense(units=6, activation='relu'))
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Tercera parte - Entrenamiento del MLP

### Compilación del MLP

In [10]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Entrenamiento del MLP en el Traning set

In [11]:
model.fit(X_train, y_train, batch_size = 100, epochs = 200)

Epoch 1/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4405 - loss: 0.7471   
Epoch 2/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4307 - loss: 0.7085 
Epoch 3/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6066 - loss: 0.6778 
Epoch 4/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.6475 
Epoch 5/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7526 - loss: 0.6184 
Epoch 6/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7846 - loss: 0.6002 
Epoch 7/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8243 - loss: 0.5948 
Epoch 8/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8427 - loss: 0.5558 
Epoch 9/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8529 - loss: 0.5339 
Epoch 10/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8534 - loss: 0.5214 
Epoch 11/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8619 - loss: 0.5041 
Epoch 12/200
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/ste

In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 6)              │            66 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 6)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 347 (1.36 KB)

 Trainable params: 115 (460.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 232 (932.00 B)

## Cuarta parte - Predicciones y evaluación del modelo 

### Predeción de nuevos resultados (los ejemplos de test que has puesto en el notebook)

In [13]:
print(model.predict(sc.transform([['0.0', '0.0', '0.0', '0.0', '286.506', '0.0', '1', '1', '6.6733766475', '40.804477488999545']])) > 0.5)

 #deberia ser falso (no ataque)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
[[False]]


In [14]:
print(model.predict(sc.transform([['0.0', '0.0', '0.0', '0.0', '0.028499999999999998', '0.00027225', '0', '2', '8.328765946499997', '69.36600139499883']])) >0.5)
#deberia ser falso (no ataque)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[False]]


In [15]:
print(model.predict(sc.transform([['0.0', '0.0', '0.0', '0.0', '0.0245', '9.025000000000003e-05', '0', '2', '15.002157899500006', '225.05562456245494']])) >0.5)
#deberia ser falso (no ataque)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[False]]


In [16]:
print(model.predict(sc.transform([['0.0', '0.0', '0.0', '0.0', '0.024999999999999998', '0.00014399999999999998', '0', '2', '15.001913046000046', '225.05168306759057']]))>0.5)
#deberia ser falso (no ataque)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[False]]


In [17]:
print(model.predict(sc.transform([['0.0', '0.0', '0.0', '0.0', '0.022', '0.0001', '0', '2', '15.00212264949997', '225.05853661176673']])) >0.5)

#deberia ser falso (no ataque)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[False]]


In [18]:
print(model.predict(sc.transform([['1.0', '3.0', '0.0', '0.0', '171105.151', '0.0', '0', '1', '22.652548496', '0.0']]))>0.5)

#deberia ser falso (no ataque)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[False]]


In [19]:
print(model.predict(sc.transform([['0.0', '0.0', '0.0', '0.0', '0.023', '0.00012100000000000003', '0', '2', '3.675669603999956', '13.50954112864207']]))>0.5)
#deberia ser falso (no ataque)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[[False]]


In [20]:
print(model.predict(sc.transform([['0','0','0','0','84.54626762','2847.118438', '886', '909', '0.000279018', '3.40E-07']])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[ True]]


In [21]:
print(model.predict(sc.transform([['0','0','0','0','29661.68829','290288630.6','50','1704','0.001032548','3.19E-05']]))>0.5)
#deberia ser verdadero, presente en el dataset

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[ True]]


In [22]:
print(model.predict(sc.transform([['0','0','0','0','67.62997351','1170.951808','147','149','0.001686923','2.89E-06']])) >0.5)


#deberia ser verdadero, presente en el dataset

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[ True]]


In [23]:
print(model.predict(sc.transform([['0','0','0','0','36.215','0','87','1','0.03400538','2.63E-05']]))>0.5)
#deberia ser verdadero, presente en el dataset


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[ True]]


In [24]:
print(model.predict(sc.transform([['0','0','0','0','36.169','0','86','1','0.03456421','6.06E-05']]))>0.5)
#deberia ser verdadero, presente en el dataset


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[ True]]


In [25]:
print(model.predict(sc.transform([['0','0','0','0','36.391','0','87','1','0.034021056','2.59E-05']]))>0.5)
#deberia ser verdadero, presente en el dataset


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[ True]]


### Predicción del Test set

In [26]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 718us/step
[[1 1]
 [1 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


### Metricas + matriz de confusión

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score 
cm = confusion_matrix(y_test, y_pred)
print(cm)
print( 'accuracy=', accuracy_score(y_test, y_pred))
print('precision =', precision_score(y_test, y_pred))
print('recall = ', recall_score(y_test, y_pred))
print('F1-score=', f1_score(y_test, y_pred))
print ('AUC_ROC score =', roc_auc_score(y_test, y_pred))

[[294   0]
 [  2 209]]
accuracy= 0.996039603960396
precision = 1.0
recall =  0.990521327014218
F1-score= 0.9952380952380953
AUC_ROC score = 0.9952606635071091


### Guardar el modelo

In [28]:
model.save('MLP_11agosto.keras') 